- task : AzureCLI@2
    inputs: 
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'C:\Program Files (x86)\TRICENTIS\Tosca Testsuite\ToscaCommander\ToscaCI\Client>ToscaCIClient.exe -m local' 

trigger:
    - master
pool:
    vmImage: ubuntu-latest
steps:
    -
        script: 'echo Hello, world!'
        displayName: 'Run a one-line script'
    -
        script: "echo Add other tasks to build, test, and deploy your project.\necho See https://aka.ms/yaml\n"
        displayName: 'Run a multi-line script'